-- SmartRent v1 foundation. Run with `supabase db push` or in the SQL editor.
create extension if not exists btree_gist with schema extensions;

create type public.user_role as enum ('RENTER', 'OWNER', 'ADMIN');
create type public.user_status as enum ('ACTIVE', 'SUSPENDED');
create type public.rental_mode as enum ('SHORT_TERM', 'LONG_TERM', 'BOTH');
create type public.property_status as enum ('PENDING', 'ACTIVE', 'REJECTED', 'INACTIVE');
create type public.availability_status as enum ('RESERVED', 'BOOKED', 'BLOCKED');
create type public.booking_status as enum ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'ACTIVE', 'COMPLETED');
create type public.lease_status as enum ('ACTIVE', 'COMPLETED', 'EXPIRED', 'TERMINATED');
create type public.notification_type as enum (
  'BOOKING_REQUEST', 'BOOKING_APPROVED', 'BOOKING_REJECTED',
  'BOOKING_CANCELLED', 'NEW_MESSAGE', 'LEASE_EXPIRING', 'SYSTEM_ALERT'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text,
  role public.user_role not null default 'RENTER',
  avatar_url text,
  status public.user_status not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint full_name_length check (char_length(full_name) <= 120)
);

create table public.properties (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null,
  address text not null,
  city text not null,
  property_type text not null,
  bedrooms smallint not null default 0 check (bedrooms >= 0),
  bathrooms numeric(3,1) not null default 0 check (bathrooms >= 0),
  max_occupants smallint not null check (max_occupants > 0),
  short_term_price numeric(12,2) check (short_term_price > 0),
  monthly_price numeric(12,2) check (monthly_price > 0),
  rental_mode public.rental_mode not null,
  status public.property_status not null default 'PENDING',
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rental_mode_has_price check (
    (rental_mode = 'SHORT_TERM' and short_term_price is not null) or
    (rental_mode = 'LONG_TERM' and monthly_price is not null) or
    (rental_mode = 'BOTH' and short_term_price is not null and monthly_price is not null)
  )
);

create table public.property_images (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  storage_path text not null unique,
  alt_text text,
  is_cover boolean not null default false,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now()
);
create unique index one_cover_per_property on public.property_images(property_id) where is_cover;

create table public.amenities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  created_at timestamptz not null default now()
);

create table public.property_amenities (
  property_id uuid not null references public.properties(id) on delete cascade,
  amenity_id bigint not null references public.amenities(id) on delete restrict,
  primary key (property_id, amenity_id)
);

-- AVAILABLE is implicit when no BLOCKED/RESERVED/BOOKED range exists.
create table public.availability (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete cascade,
  booking_id uuid,
  start_date date not null,
  end_date date not null,
  status public.availability_status not null,
  reason text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  constraint availability_dates_valid check (end_date > start_date),
  constraint availability_source_valid check (
    (status = 'BLOCKED' and booking_id is null) or
    (status in ('RESERVED', 'BOOKED') and booking_id is not null)
  )
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties(id) on delete restrict,
  renter_id uuid not null references public.profiles(id) on delete restrict,
  owner_id uuid not null references public.profiles(id) on delete restrict,
  rental_mode public.rental_mode not null check (rental_mode <> 'BOTH'),
  start_date date not null,
  end_date date not null,
  occupants smallint not null check (occupants > 0),
  estimated_cost numeric(12,2) not null check (estimated_cost >= 0),
  status public.booking_status not null default 'PENDING',
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint booking_dates_valid check (end_date > start_date),
  constraint renter_not_owner check (renter_id <> owner_id),
  constraint no_overlapping_live_bookings exclude using gist (
    property_id with =,
    daterange(start_date, end_date, '[)') with &&
  ) where (status in ('PENDING', 'APPROVED', 'ACTIVE'))
);

alter table public.availability
  add constraint availability_booking_fk foreign key (booking_id)
  references public.bookings(id) on delete cascade;

create table public.leases (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null unique references public.bookings(id) on delete restrict,
  property_id uuid not null references public.properties(id) on delete restrict,
  renter_id uuid not null references public.profiles(id) on delete restrict,
  owner_id uuid not null references public.profiles(id) on delete restrict,
  monthly_rent numeric(12,2) not null check (monthly_rent > 0),
  start_date date not null,
  end_date date not null,
  status public.lease_status not null default 'ACTIVE',
  expiry_reminder_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lease_dates_valid check (end_date > start_date)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.properties(id) on delete cascade,
  booking_id uuid references public.bookings(id) on delete set null,
  content text not null check (char_length(trim(content)) between 1 and 5000),
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  constraint message_participants_differ check (sender_id <> receiver_id)
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type public.notification_type not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index properties_public_search_idx on public.properties(status, city, rental_mode);
create index properties_owner_idx on public.properties(owner_id, created_at desc);
create index bookings_renter_idx on public.bookings(renter_id, created_at desc);
create index bookings_owner_idx on public.bookings(owner_id, status, created_at desc);
create index availability_property_dates_idx on public.availability(property_id, start_date, end_date);
create index messages_participants_idx on public.messages(sender_id, receiver_id, created_at desc);
create index notifications_user_idx on public.notifications(user_id, is_read, created_at desc);

create function public.set_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger properties_set_updated_at before update on public.properties
for each row execute function public.set_updated_at();
create trigger bookings_set_updated_at before update on public.bookings
for each row execute function public.set_updated_at();
create trigger leases_set_updated_at before update on public.leases
for each row execute function public.set_updated_at();

create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  requested_role public.user_role;
begin
  requested_role := case
    when new.raw_user_meta_data ->> 'role' = 'OWNER' then 'OWNER'::public.user_role
    else 'RENTER'::public.user_role
  end;

  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), requested_role);
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create function public.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'ADMIN' and status = 'ACTIVE'
  );
$$;

create function public.protect_profile_privileges() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if (select auth.uid()) is not null and not public.is_admin() then
    new.role := old.role;
    new.status := old.status;
  end if;
  return new;
end;
$$;
create trigger profiles_protect_privileges before update on public.profiles
for each row execute function public.protect_profile_privileges();

create function public.validate_booking_write() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  selected_property public.properties%rowtype;
  actor uuid := (select auth.uid());
  actor_role public.user_role;
begin
  if tg_op = 'INSERT' then
    perform pg_advisory_xact_lock(hashtextextended(new.property_id::text, 0));
    select * into selected_property from public.properties where id = new.property_id;
    select role into actor_role from public.profiles where id = actor and status = 'ACTIVE';

    if actor is not null and (actor <> new.renter_id or actor_role <> 'RENTER') then
      raise exception 'Only an active renter can create their own booking';
    end if;
    if selected_property.id is null or selected_property.status <> 'ACTIVE' then
      raise exception 'Property is not available for booking';
    end if;
    if selected_property.owner_id <> new.owner_id or new.renter_id = new.owner_id then
      raise exception 'Booking participants do not match the property';
    end if;
    if new.occupants > selected_property.max_occupants then
      raise exception 'Occupant count exceeds the property limit';
    end if;
    if not (
      selected_property.rental_mode = 'BOTH' or selected_property.rental_mode = new.rental_mode
    ) then
      raise exception 'Selected rental mode is not supported';
    end if;
    if exists (
      select 1 from public.availability a
      where a.property_id = new.property_id and a.status = 'BLOCKED'
        and daterange(a.start_date, a.end_date, '[)') && daterange(new.start_date, new.end_date, '[)')
    ) then
      raise exception 'Selected dates are blocked';
    end if;
    new.status := 'PENDING';
    new.estimated_cost := case new.rental_mode
      when 'SHORT_TERM' then (new.end_date - new.start_date) * selected_property.short_term_price
      when 'LONG_TERM' then greatest(1, ceil((new.end_date - new.start_date) / 30.0)) * selected_property.monthly_price
      else 0
    end;
  elsif actor is not null and not public.is_admin() then
    if actor = old.owner_id then
      if old.status <> 'PENDING' or new.status not in ('APPROVED', 'REJECTED') then
        raise exception 'Owner can only approve or reject a pending booking';
      end if;
    elsif actor = old.renter_id then
      if old.status not in ('PENDING', 'APPROVED') or new.status <> 'CANCELLED' then
        raise exception 'Renter can only cancel an eligible booking';
      end if;
    else
      raise exception 'Not authorized to update this booking';
    end if;

    new.property_id := old.property_id;
    new.renter_id := old.renter_id;
    new.owner_id := old.owner_id;
    new.rental_mode := old.rental_mode;
    new.start_date := old.start_date;
    new.end_date := old.end_date;
    new.occupants := old.occupants;
    new.estimated_cost := old.estimated_cost;
  end if;
  return new;
end;
$$;
create trigger bookings_validate_write before insert or update on public.bookings
for each row execute function public.validate_booking_write();

create function public.sync_booking_side_effects() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    insert into public.availability
      (property_id, booking_id, start_date, end_date, status, created_by)
    values
      (new.property_id, new.id, new.start_date, new.end_date, 'RESERVED', new.renter_id);
    insert into public.notifications (user_id, type, title, message, metadata)
    values (new.owner_id, 'BOOKING_REQUEST', 'New booking request',
      'A renter submitted a booking request for your property.', jsonb_build_object('booking_id', new.id));
  elsif new.status is distinct from old.status then
    if new.status = 'APPROVED' then
      update public.availability set status = 'BOOKED' where booking_id = new.id;
    elsif new.status in ('REJECTED', 'CANCELLED') then
      delete from public.availability where booking_id = new.id;
    end if;

    if new.status in ('APPROVED', 'REJECTED', 'CANCELLED') then
      insert into public.notifications (user_id, type, title, message, metadata)
      values (
        case when new.status = 'CANCELLED' then new.owner_id else new.renter_id end,
        case new.status
          when 'APPROVED' then 'BOOKING_APPROVED'::public.notification_type
          when 'REJECTED' then 'BOOKING_REJECTED'::public.notification_type
          else 'BOOKING_CANCELLED'::public.notification_type
        end,
        initcap(lower(new.status::text)) || ' booking',
        'Booking status changed to ' || new.status::text || '.',
        jsonb_build_object('booking_id', new.id)
      );
    end if;
  end if;
  return new;
end;
$$;
create trigger bookings_sync_side_effects after insert or update on public.bookings
for each row execute function public.sync_booking_side_effects();

create function public.owns_property(target_property_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.properties
    where id = target_property_id and owner_id = (select auth.uid())
  );
$$;

create function public.protect_property_moderation() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if (select auth.uid()) is not null and not public.is_admin() then
    new.status := old.status;
    new.rejection_reason := old.rejection_reason;
  end if;
  return new;
end;
$$;
create trigger properties_protect_moderation before update on public.properties
for each row execute function public.protect_property_moderation();

create function public.validate_availability_write() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended(new.property_id::text, 0));
  if new.status = 'BLOCKED' and exists (
    select 1 from public.bookings b
    where b.property_id = new.property_id
      and b.status in ('PENDING', 'APPROVED', 'ACTIVE')
      and daterange(b.start_date, b.end_date, '[)') && daterange(new.start_date, new.end_date, '[)')
  ) then
    raise exception 'Cannot block dates reserved by a live booking';
  end if;
  return new;
end;
$$;
create trigger availability_validate_write before insert or update on public.availability
for each row execute function public.validate_availability_write();

grant execute on function public.is_admin() to authenticated;
grant execute on function public.owns_property(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.property_images enable row level security;
alter table public.amenities enable row level security;
alter table public.property_amenities enable row level security;
alter table public.availability enable row level security;
alter table public.bookings enable row level security;
alter table public.leases enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;

create policy "profiles visible to authenticated users" on public.profiles
for select to authenticated using (true);
create policy "users update own profile" on public.profiles
for update to authenticated using (id = (select auth.uid()))
with check (id = (select auth.uid()));
create policy "admins manage profiles" on public.profiles
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "active properties are public" on public.properties
for select using (status = 'ACTIVE' or owner_id = (select auth.uid()) or public.is_admin());
create policy "owners create properties" on public.properties
for insert to authenticated with check (
  owner_id = (select auth.uid()) and
  exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'OWNER' and status = 'ACTIVE')
);
create policy "owners update own properties" on public.properties
for update to authenticated using (owner_id = (select auth.uid()))
with check (owner_id = (select auth.uid()));
create policy "admins moderate properties" on public.properties
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "owners delete own inactive properties" on public.properties
for delete to authenticated using (owner_id = (select auth.uid()) and status <> 'ACTIVE');

create policy "images follow property visibility" on public.property_images
for select using (exists (select 1 from public.properties p where p.id = property_id));
create policy "owners manage property images" on public.property_images
for all to authenticated using (public.owns_property(property_id)) with check (public.owns_property(property_id));
create policy "amenities are public" on public.amenities for select using (true);
create policy "admins manage amenities" on public.amenities
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "property amenities are public" on public.property_amenities for select using (true);
create policy "owners manage property amenities" on public.property_amenities
for all to authenticated using (public.owns_property(property_id)) with check (public.owns_property(property_id));

create policy "availability follows property visibility" on public.availability
for select using (exists (select 1 from public.properties p where p.id = property_id));
create policy "owners manage blocked availability" on public.availability
for all to authenticated using (public.owns_property(property_id) and status = 'BLOCKED')
with check (public.owns_property(property_id) and status = 'BLOCKED');

create policy "booking participants can read" on public.bookings
for select to authenticated using (renter_id = (select auth.uid()) or owner_id = (select auth.uid()) or public.is_admin());
create policy "renters create own bookings" on public.bookings
for insert to authenticated with check (
  renter_id = (select auth.uid()) and
  exists (select 1 from public.profiles where id = (select auth.uid()) and role = 'RENTER' and status = 'ACTIVE')
);
create policy "participants update bookings" on public.bookings
for update to authenticated using (renter_id = (select auth.uid()) or owner_id = (select auth.uid()) or public.is_admin());

create policy "lease participants can read" on public.leases
for select to authenticated using (renter_id = (select auth.uid()) or owner_id = (select auth.uid()) or public.is_admin());
create policy "owners manage leases" on public.leases
for all to authenticated using (owner_id = (select auth.uid()) or public.is_admin())
with check (owner_id = (select auth.uid()) or public.is_admin());

create policy "message participants can read" on public.messages
for select to authenticated using (sender_id = (select auth.uid()) or receiver_id = (select auth.uid()));
create policy "users send their messages" on public.messages
for insert to authenticated with check (sender_id = (select auth.uid()));
create policy "receivers mark messages read" on public.messages
for update to authenticated using (receiver_id = (select auth.uid())) with check (receiver_id = (select auth.uid()));
create policy "users read notifications" on public.notifications
for select to authenticated using (user_id = (select auth.uid()));
create policy "users update notifications" on public.notifications
for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

insert into public.amenities (name, icon) values
  ('Wi-Fi', 'Wifi'), ('Parking', 'Car'), ('Air Conditioning', 'Snowflake'),
  ('Heating', 'Flame'), ('Kitchen', 'CookingPot'), ('Furnished', 'Armchair'),
  ('Gym', 'Dumbbell'), ('Pool', 'Waves'), ('Pet Friendly', 'PawPrint'),
  ('Security', 'ShieldCheck')
on conflict (name) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('property-images', 'property-images', true, 10485760, array['image/jpeg', 'image/png', 'image/webp']),
  ('profile-images', 'profile-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy "public reads property images" on storage.objects
for select using (bucket_id = 'property-images');
create policy "owners upload property images" on storage.objects
for insert to authenticated with check (
  bucket_id = 'property-images' and
  public.owns_property(((storage.foldername(name))[1])::uuid)
);
create policy "owners update property images" on storage.objects
for update to authenticated using (
  bucket_id = 'property-images' and public.owns_property(((storage.foldername(name))[1])::uuid)
);
create policy "owners delete property images" on storage.objects
for delete to authenticated using (
  bucket_id = 'property-images' and public.owns_property(((storage.foldername(name))[1])::uuid)
);
create policy "public reads profile images" on storage.objects
for select using (bucket_id = 'profile-images');
create policy "users upload own profile images" on storage.objects
for insert to authenticated with check (
  bucket_id = 'profile-images' and (storage.foldername(name))[1] = (select auth.uid())::text
);
create policy "users update own profile images" on storage.objects
for update to authenticated using (
  bucket_id = 'profile-images' and (storage.foldername(name))[1] = (select auth.uid())::text
);
create policy "users delete own profile images" on storage.objects
for delete to authenticated using (
  bucket_id = 'profile-images' and (storage.foldername(name))[1] = (select auth.uid())::text
);
